spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: 123456

logging:
  level:
    org:
      springframework:
        web: info
    com:
      company:
        demo: debug