alias ga='git add'
alias gaa='git add .'
alias gc='git commit -m'
alias gca='git commit -m "update"'
alias gl='git log --all'
alias gd='git diff --name-only --cached'
alias gf='git pull'
alias gp='git push'
alias gr='git reset'
alias grh='git reset --hard'
alias grm='git reset --mixed'
alias grs'git reset --soft'

alias ra='ranger'
alias s='archey3'

